spring.application.name=AppKartingRM
server.port=8080


# Config base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/kartingRM
spring.datasource.username=postgres
spring.datasource.password=1234
# Tipo de acceso a la base de datos: create, create-drop, update
spring.jpa.hibernate.ddl-auto=update