spring.application.name=AppKartingRM
server.port=8090


# Config base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/kartingRM
# Usar variables de entorno, entre otros, evita filtrar informacion importante
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Tipo de acceso a la base de datos: create, create-drop, update
spring.jpa.hibernate.ddl-auto=update
